alfresco:
  image: alfresco-standalone-cors
  ports:
   - "8080:8080"
  links:
   - postgres:postgres
postgres:
  image: postgres:latest
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco